insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (001, 0,'kila',5000,'2019-02-01',1,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (002, 0,'jila',8000,'2019-03-01',2,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (003, 0,'kulla',8500,'2019-03-01',3,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (004, 0,'kachi',5600,'2019-03-01',4,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (005, 0,'banchi',9000,'2019-03-01',5,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (006, 0,'lonchi',12000,'2019-03-01',6,null,null);
insert into PROFESSOR (ID,DELETED,NAME,SALARY,START_DATE,ADDRESS_ID,DEPARTMENT_ID,MANAGER_ID) values (007, 0,'banga',12000,'2019-05-09',null,null,null);

insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (001,'Kochi',0,'Kerala','Alagar st',741103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (002,'Renugunda',0,'Andhra','Thillai st',541103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (003,'Aurangabad',0,'Maharashtra','Thakre st',241103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (004,'Silluguri',0,'West Bengal','Nanasab st',331103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (005,'Jaipur',0,'Rajesthan','kanup st',554103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (006,'Sillong',0,'Assam','Ruble st', 84103);
insert into ADDRESS (ID,CITY,DELETED,STATE,STREET,ZIP) values (007,'Jamsedpur',0,'Bihar','Kaur st', 86703);

insert into PHONE (ID,NUMBER,TYPE,EMPLOYEE_ID) values (001,987563482,'Home',1);
insert into PHONE (ID,NUMBER,TYPE,EMPLOYEE_ID) values (001,987233482,'Work',1);
insert into PHONE (ID,NUMBER,TYPE,EMPLOYEE_ID) values (001,6787233482,'Guest House',1);

Select NAME, SALARY, STREET, CITY, STATE, ZIP 
from PROFESSOR p, ADDRESS a 
where p.ADDRESS_ID = a.ID

Select NAME, SALARY, STREET, CITY, STATE, ZIP 
from PROFESSOR p
LEFT JOIN ADDRESS a 
on p.ADDRESS_ID = a.ID

SELECT NAME, CITY, NUMBER 
from PROFESSOR p LEFT JOIN ADDRESS a ON p.ADDRESS_ID = a.ID 
LEFT JOIN PHONE pe ON p.ADDRESS_ID = pe.EMPLOYEE_ID


SELECT NAME, CITY, NUMBER 
from PROFESSOR p INNER JOIN ADDRESS a ON p.ADDRESS_ID = a.ID 
INNER JOIN PHONE pe ON p.ADDRESS_ID = pe.EMPLOYEE_ID

--self join
SELECT p1.NAME, p1.SALARY 
from PROFESSOR p1, PROFESSOR p2
where p1.SALARY < p2.SALARY









